export const MOST_LIKELY_TO = [
  `Most likely to disappear from the group chat for 3 months straight.`,
  `Most likely to ghost their crush after one good convo.`,
  `Most likely to be secretly judging everyone in silence.`,
  `Most likely to read messages and never respond.`,
  `Most likely to get banned from a party for doing something stupid.`,
  `Most likely to start chaos just for fun.`,
  `Most likely to turn a serious conversation into a meme fest.`,
  `Most likely to laugh at a funeral (inappropriately).`,
  `Most likely to build a robot to do their chores.`,
  `Most likely to argue with a professor and win.`,
  `Most likely to finish the group project alone.`,
  `Most likely to explain why your code doesn’t work — unprovoked.`,
  `Most likely to have a mental breakdown over a phone update.`,
  `Most likely to be mad and not know why.`,
  `Most likely to go from 'life is meaningless' to 'I’m gonna change the world' in 5 mins.`,
  `Most likely to pick a fight in traffic... with a keke driver.`,
  `Most likely to beat someone up for touching their sibling.`,
  `Most likely to pretend not to care — but actually care too much.`,
  `Most likely to give 'wise elder sibling' advice and then ignore it themselves.`,
  `Most likely to be everyone's unofficial therapist.`,
  `Most likely to cry over an anime death.`,
  `Most likely to start a playlist war.`,
  `Most likely to talk about an anime scene like it happened to them.`,
  `Most likely to judge you for your music taste — harshly.`,
  `Most likely to call Jollof rice 'mid' just to cause chaos.`,
  `Most likely to curse NEPA when the light goes off.`,
  `Most likely to fake an accent after one week abroad.`,
  `Most likely to get roasted by their mom for breathing too loudly.`,
  `Most likely to ask what day it is during an exam.`,
  `Most likely to get hacked by a phishing email that says 'click here for free plantain.'`,
  `Most likely to argue confidently — and be completely wrong.`,
  `Most likely to catch feelings after a one-night stand.`,
  `Most likely to be a virgin and still give the best sex advice.`,
  `Most likely to have a secret OnlyFans account — and it’s poppin'.`,
  `Most likely to be into some freaky anime stuff.`,
  `Most likely to send a risky snap and then panic for 2 hours.`,
  `Most likely to moan accidentally while stretching.`,
  `Most likely to risk it all for someone with 3 red flags and a good smile.`,
  `Most likely to have 'horny hours' scheduled like calendar events.`,
  `Most likely to fake an orgasm out of boredom.`,
  `Most likely to say 'just the tip' and lie.`,
  `Most likely to hack their school just to change their GPA.`,
  `Most likely to argue with ChatGPT and win.`,
  `Most likely to build a robot and treat it better than humans.`,
  `Most likely to stay up all night learning a useless programming language.`,
  `Most likely to correct your grammar mid-breakdown.`,
  `Most likely to make a joke at a funeral... and make it land.`,
  `Most likely to laugh alone at their own meme at 3 AM.`,
  `Most likely to roast you with facts and logic.`,
  `Most likely to fake their own death just to see who shows up.`,
  `Most likely to get canceled for something they said ironically.`,
  `Most likely to write a 10-page essay and delete it before sending.`,
  `Most likely to ghost everyone and claim it's 'self-care.'`,
  `Most likely to look dead inside but be top of the class.`,
  `Most likely to cry during a system update.`,
  `Most likely to diagnose everyone else's mental illness correctly.`,
  `Most likely to skip a party to finish a side project no one asked for.`,
  `Most likely to have a crush on a fictional character.`,
  `Most likely to wear the same hoodie for 2 years.`,
  `Most likely to call Stack Overflow their therapist.`,
  `Most likely to have 10 backup plans for a date they’ll never get.`,
  `Most likely to scold you like a dad but still steal your snacks.`,
  `Most likely to be the group's tech support and hate it.`,
  `Most likely to yell 'Save your work!' every 10 minutes.`,
  `Most likely to pretend they're fine when their world is on fire.`,
  `Most likely to say 'back in my day' at 24.`,
  `Most likely to start a debate and walk away mid-argument.`,
  `Most likely to protect you from a fight *they* started.`,
  `Most likely to laugh during a serious conversation.`,
  `Most likely to give amazing advice and not take it themselves.`,
  `Most likely to be arguing, crying, and coding — all at once.`,
  `Most likely to use 'it is well' to avoid actual solutions.`,
  `Most likely to say 'God abeg' instead of doing the assignment.`,
  `Most likely to be broke and still flex new shoes.`,
  `Most likely to write a 2000-word rant about NEPA (power outage).`,
  `Most likely to drop out of uni to become a crypto guru.`,
  `Most likely to forget what day it is during exams.`,
  `Most likely to cry over grades they didn't even check.`,
  `Most likely to develop a full mental health condition over a 2-credit course.`,
  `Most likely to fall in love with someone they’ve never talked to.`,
  `Most likely to sleep through a final and call it 'God's plan.'`,
  `Most likely to make a playlist for every emotion.`,
  `Most likely to sing anime openings in the shower like it's a concert.`,
  `Most likely to argue that 'Jujutsu Kaisen' is a personality trait.`,
  `Most likely to cry over an anime death for 3-5 business days.`,
  `Most likely to quote song lyrics instead of speaking normally.`,
  `Most likely to speak once and change the vibe of the room.`,
  `Most likely to yell for no reason and walk away like nothing happened.`,
  `Most likely to take 30 seconds to answer a yes/no question.`,
  `Most likely to beat someone up for touching their friend’s food.`,
  `Most likely to sit in silence the whole day but notice everything.`,
  `Most likely to say 'everything’s fine' during an apocalypse.`,
  `Most likely to assume the worst from a 'hi' text.`,
  `Most likely to fix your life while theirs is burning in the background.`,
  `Most likely to say 'trust the process' and cry the whole way.`,
  `Most likely to think the group project is a sign from God that life is over.`,
  `Most likely to risk it all for someone with bad grammar and nice thighs.`,
  `Most likely to send 'wyd?' and actually mean 'ruin my life.'`,
  `Most likely to fall in love after one anime recommendation and a hug.`,
  `Most likely to have a playlist titled 'things I’d do to you (if I had game).'`,
  `Most likely to moan louder over food than during sex.`,
  `Most likely to watch hentai 'for the plot.'`,
  `Most likely to accidentally send a thirst trap to the class group chat.`,
  `Most likely to flirt using anime references and still pull.`,
  `Most likely to have a situationship they pray about.`,
  `Most likely to say 'I’m not looking for anything serious' and catch feelings 12 minutes later.`,
  `Most likely to ghost someone they’re in love with, for 'mental health.'`,
  `Most likely to act celibate but have unspoken demon time energy.`,
  `Most likely to nut and then open LeetCode.`,
  `Most likely to flex their lack of physical affection like it’s an achievement.`,
  `Most likely to use 'I’m a virgin' as both a defense and a flex.`,
  `Most likely to have their AirPods in during head.`,
  `Most likely to overthink sex until it feels like a group project.`,
  `Most likely to reply 'k' to a nude.`,
  `Most likely to send 3 memes after sexting to break the tension.`,
  `Most likely to beg for nudes with Shakespearean energy.`,
  `Most likely to fall in love with their straight friend — again.`,
  `Most likely to be homophobic as a coping mechanism.`,
  `Most likely to flirt, cry, and disassociate — in that order.`,
  `Most likely to say “I hate men” while texting five.`,
  `Most likely to have a breakup playlist longer than their relationship.`,
  `Most likely to ghost someone because they were too nice.`,
  `Most likely to turn every compliment into an identity crisis.`,
  `Most likely to seduce and insult someone in the same sentence.`,
  `Most likely to use fashion as a weapon and therapy.`,
  `Most likely to say “this is so homophobic” when the vending machine eats their money.`,
  `Most likely to rewatch a queer movie just to cry over the tragic ending.`,
  `Most likely to date someone with the same trauma for synergy.`,
  `Most likely to respond to “wyd?” with “being gay and dramatic.”`,
  `Most likely to thirst over animated men and be proud of it.`,
];

export const TWO_TRUTHS_AND_A_LIE = [
  `Tell us about a time you completely embarrassed yourself in public.`,
  `Share a moment where you snapped unexpectedly.`,
  `What’s something you’ve Googled late at night that made you question your own sanity or identity?`,
  `Describe the most ridiculous thing you've done to impress someone and failed.`,
  `Talk about the worst decision you made under pressure.`,
  `Reveal the weirdest thing you've ever said or done while angry.`,
  `Describe a time you felt like a main character in an anime.`,
  `What’s a secret obsession or habit you’ve had that no one knew about?`,
  `Talk about a time you faked confidence and somehow pulled it off.`,
  `Share a romantic experience that didn't go the way you expected.`,
  `Describe the most awkward conversation you've had with a stranger.`,
  `What's a lie you once told that got out of hand?`,
  `Share a time you felt completely out of place in a group setting.`,
  `Talk about a time you failed miserably at something you were sure you’d be great at.`,
  `What’s the most extreme thing you've done out of boredom?`,
  `Describe a time you got blamed for something you didn't do.`,
  `What’s something childish you still secretly enjoy?`,
  `Share a moment when your emotions completely took over.`,
  `Talk about a time you were sure you were right… but were completely wrong.`,
  `What’s something you’ve destroyed out of anger or impulse?`,
  `Describe the strangest dream you've ever had.`,
  `Share a guilty pleasure you’re embarrassed to admit.`,
  `Talk about a time you ruined something important — accidentally or not.`,
  `What’s a moment you wanted the ground to swallow you up?`,
  `Describe a time you stood up for someone (or didn't and regret it).`,
  `What’s a time you pretended to know something you actually didn’t?`,
  `Share a moment when you made someone laugh without meaning to.`,
  `Describe the most spontaneous thing you’ve ever done.`,
  `Talk about the pettiest reason you ever got mad at someone.`,
  `What’s a time you got caught lying and had to think fast?`,
  `Share a time you avoided a responsibility and it came back to bite you.`,
  `What’s a big secret you kept from your parents or guardians growing up?`,
  `Describe a moment when you broke a rule and loved it.`,
  `What’s the most embarrassing thing on your search history?`,
  `Talk about a time when you made up a story on the spot and people believed it.`,
  `Share the most extreme emotional reaction you had to something small.`,
  `What’s a really stupid thing you believed as a child?`,
  `Describe a time when you made a terrible first impression.`,
  `Talk about a time you tried to act cool and it completely backfired.`,
  `What’s something weird you used to be *convinced* was normal?`,
  `Share a time you got involved in drama that had nothing to do with you.`,
  `Describe the most random thing you've cried about.`,
  `Talk about the most impulsive purchase you've made.`,
  `What's something you've pretended to enjoy because everyone else did?`,
  `Share a time you got away with doing something *very* questionable.`,
  `Talk about a time you sabotaged yourself without realizing.`,
  `What’s the most cringe thing you've ever texted someone?`,
  `Describe a moment when your brain just completely shut down.`,
  `Share a time you laughed at the *worst possible* moment.`,
  `What's something you still regret doing in secondary school or uni?`,
];

export const WOULD_YOU_RATHER = [
  `Would you rather fight 100 tiny versions of yourself or one giant version of yourself?`,
  `Would you rather lose access to the internet for a year or be forced to write all your essays by hand for life?`,
  `Would you rather live in an anime world forever or be able to turn into any anime character once a week?`,
  `Would you rather be stuck in a silent room with the Loud friend or be stuck in a loud concert with the Silent friend?`,
  `Would you rather be extremely intelligent but socially awkward or very charming but below average intelligence?`,
  `Would you rather your search history be made public or your private thoughts be broadcasted randomly once a day?`,
  `Would you rather be respected like an elder brother or envied like a villain?`,
  `Would you rather be unhinged in public for a week or reserved but constantly roasted by everyone around you?`,
  `Would you rather only be able to speak in anime quotes or rap lyrics?`,
  `Would you rather get hacked by a Computer Geek or roasted by the Joker friend?`,
  `Would you rather always feel like you just drank 5 cups of coffee (ADHD vibes) or always feel like you're moving in slow motion?`,
  `Would you rather take a class with a Professor who speaks like a Shakespearean play or like a Gen Z TikToker?`,
  `Would you rather your mood swings be controlled by a dice roll or by your worst enemy?`,
  `Would you rather have a protective friend stalk your crush or a passive friend accidentally leak your secrets?`,
  `Would you rather be stuck in a room with a depressed person for a week or with someone with extreme anger issues?`,
  `Would you rather have music playing in your head nonstop or never be able to listen to music again?`,
  `Would you rather be an eternal university student or a dropout who becomes a millionaire?`,
  `Would you rather watch your favorite anime get a horrible live-action adaptation or get cancelled after a cliffhanger?`,
  `Would you rather be caught crying by your crush or caught doing something totally weird by your professor?`,
  `Would you rather live your life as a meme or as a serious documentary?`,
  `Would you rather your gay friend be your wingman forever or your mood-swinging friend be your roommate forever?`,
  `Would you rather only be able to communicate in riddles or only be able to scream your thoughts?`,
  `Would you rather take a test with ADHD focus or hang out with your pessimistic friend during a crisis?`,
  `Would you rather have to lecture the unhinged friend every day or take a slow (mentally) friend to every exam?`,
  `Would you rather get roasted in a group chat or have a one-on-one with the most nonchalant person alive?`,
  `Would you rather have one chance to become a genius or unlimited chances to be funny?`,
  `Would you rather your depression turn into a musical or your ADHD become contagious?`,
  `Would you rather attend a music concert for a genre you hate or be forced to binge a boring anime?`,
  `Would you rather be a Nigerian prince with no money or a broke student with unlimited jollof rice?`,
  `Would you rather date someone your friends all hate or be single forever?`,
  `Would you rather have your entire life narrated by Morgan Freeman or turned into a stand-up set by your Comedian friend?`,
  `Would you rather always get caught doing something weird or always say the wrong thing at the wrong time?`,
  `Would you rather have a super slow brain but high emotional intelligence, or be a genius with no social awareness?`,
  `Would you rather get stuck in a group project with a passive person or someone with mood swings?`,
  `Would you rather confess your love through a PowerPoint or through an anime-style confession scene?`,
  `Would you rather have your favorite song deleted forever or your most embarrassing memory go viral?`,
  `Would you rather every exam be an oral exam with your strictest lecturer or a practical exam led by your ADHD friend?`,
  `Would you rather your anger issues be triggered by memes or motivational quotes?`,
  `Would you rather be known as the Virgin with a god complex or the Gay Icon with no dating game?`,
  `Would you rather be super hardworking but get no recognition, or do nothing and be praised for it?`,
  `Would you rather debate a nerd on Star Wars lore or an anime fan on Naruto’s power scaling?`,
  `Would you rather have your protective friend fight all your battles or your joker friend roast all your enemies?`,
  `Would you rather switch bodies with the loud friend for a day or the silent one for a month?`,
  `Would you rather always be optimistic and wrong or pessimistic and right?`,
  `Would you rather be mentally slow but physically fit or mentally sharp but physically weak?`,
  `Would you rather live your life as an anime filler arc or a season finale?`,
  `Would you rather your entire family follow your social media or your university lecturer?`,
  `Would you rather only be able to eat food from Nigerian cafeterias forever or only eat instant noodles?`,
  `Would you rather relive your worst heartbreak or rewatch the worst anime you’ve ever seen 10 times?`,
  `Would you rather always have to explain memes to the slow friend or have to explain emotions to the nonchalant friend?`,
];

export const HOT_TAKES = [
  `Crying is a strength, not a weakness.`,
  `Therapy is more necessary than school for most people.`,
  `If you're not a little bit mentally ill, you're boring.`,
  `Mood swings are just personality plot twists.`,
  `Depression memes are valid coping mechanisms.`,
  `Emotional detachment is better than constant vulnerability.`,
  `Being “mysterious” is just emotional constipation.`,
  `You don’t have to forgive people to heal.`,
  `If you don’t overshare at least once a month, you’re bottling too much.`,
  `Being clingy is just a love language with bad PR.`,
  `Smart people tend to be the most emotionally unstable.`,
  `School suppresses creativity more than it nurtures it.`,
  `Being book smart is useless if you’re socially dumb.`,
  `Procrastinators are more intelligent than early birds.`,
  `Grades say more about your discipline than your intelligence.`,
  `Being the "top student" is a trauma response.`,
  `ADHD is a superpower when you actually care about something.`,
  `The education system is a punishment, not preparation.`,
  `Being slow to understand doesn’t make you less capable.`,
  `People who study last minute and pass are the real geniuses.`,
  `Dark humor is a sign of high intelligence.`,
  `Unhinged friends are more loyal than the chill ones.`,
  `Oversharing trauma is a valid comedic strategy.`,
  `Insults between friends are proof of real love.`,
  `If you're not slightly feral, are you even fun?`,
  `Making jokes at funerals should be socially acceptable.`,
  `The “funny friend” is usually the most broken inside.`,
  `Mocking your friends is a form of affection.`,
  `Sometimes a villain arc is necessary for character development.`,
  `Humor is more important than empathy in friendships.`,
  `Sexuality is fluid for more people than they admit.`,
  `Hypermasculinity is just emotional repression in disguise.`,
  `Being gay is not a personality trait—but it *can* be fun.`,
  `Straight men should compliment their homies more.`,
  `Gender roles are a social scam.`,
  `If you’ve never questioned your sexuality, you’re lying.`,
  `Labels are helpful until they become cages.`,
  `Asexuality is not a “lack of experience.”`,
  `Everyone is a little bit gay—some just fear it.`,
  `Masculine-presenting people should wear skirts more.`,
  `Anime teaches more life lessons than school ever did.`,
  `Villains are usually more relatable than heroes.`,
  `Binge-watching anime at 3am *is* self-care.`,
  `Internet friends > real life friends.`,
  `Being chronically online is better than being socially available.`,
  `TikTok is the new therapist.`,
  `“Touch grass” is an insult *and* a genuine suggestion.`,
  `Waifus and husbandos are emotional support systems.`,
  `You don't *really* love anime if you watch only shonen.`,
  `Fanfic writers deserve more respect than published authors.`,
  `Falling in love ruins your life more often than it helps it.`,
  `Loyalty is overrated—respect is more important.`,
  `You *can* love someone and still be toxic for them.`,
  `Some friendships are meant to expire like milk.`,
  `People who ghost are just emotionally lazy.`,
  `Jealousy is a natural part of friendship.`,
  `It's okay to choose yourself over your family.`,
  `Being too nice is a character flaw.`,
  `Closure is a myth—ghosting is sometimes mercy.`,
  `If someone wrongs you, revenge is sometimes justified.`,
  `Nigerian parents are emotionally unavailable by default.`,
  `“Respect your elders” is often an excuse for abuse.`,
  `Nigeria stifles creativity more than it encourages it.`,
  `Slapping your child is not discipline—it’s trauma.`,
  `Most Nigerian pastors should be in jail.`,
  `Therapy is more needed in Nigeria than church.`,
  `Being Nigerian automatically comes with a personality disorder.`,
  `“You’re too soft” is Nigerian for “you have emotions.”`,
  `Jollof rice is overrated (don’t fight me).`,
  `Nigerian men are allergic to accountability.`,
  `The talking stage is the worst part of relationships.`,
  `You can have romantic feelings for more than one person at a time.`,
  `Platonic soulmates exist and are more important than romantic ones.`,
  `Most relationships end because of timing, not lack of love.`,
  `Friends should be allowed to date without drama.`,
  `A situationship is still a relationship.`,
  `The friendzone isn’t real—just entitlement in disguise.`,
  `Love is more about timing than compatibility.`,
  `“Forever” is delusional; love is a phase.`,
  `Every crush is a minor form of mental illness.`,
  `Every friend group needs one mentally unstable member.`,
  `If you haven’t threatened to disappear, are you even depressed?`,
  `Drinking water is a scam invented by Big Hydration.`,
  `Sleep is optional when vibes are immaculate.`,
  `Arguing is a valid love language.`,
  `If they can't handle your worst, make it worse.`,
  `Ghosting is just digital teleportation.`,
  `If you're not the main character, you're an NPC.`,
  `Every friendship needs at least one near-death story.`,
  `Pain is temporary, but chaos is eternal.`,
];

export const HOW_WELL_DO_YOU_KNOW_ME = [
  `What time do I usually go to bed?`,
  `Am I more of a morning person or night owl?`,
  `How do I usually respond when I’m overwhelmed?`,
  `What’s my default comfort activity when I’m mentally drained?`,
  `Do I prefer being indoors or outdoors?`,
  `What’s one thing I do every single day without fail?`,
  `What’s my most used app?`,
  `Do I work better in silence or with background noise?`,
  `Do I think more logically or emotionally?`,
  `Would I rather plan everything or go with the flow?`,
  `What’s my favorite music genre?`,
  `Who’s my favorite anime character of all time?`,
  `Do I prefer strategy games, shooters, or story-based games?`,
  `Which season of the year do I love the most?`,
  `What’s my go-to comfort food or snack?`,
  `What type of humor cracks me up the most?`,
  `Am I more of a visual, auditory, or hands-on learner?`,
  `What’s my favorite subject or topic to nerd out about?`,
  `Do I prefer books, movies, or anime?`,
  `What’s one fandom I’ve never left?`,
  `When I’m upset, do I talk it out or go silent?`,
  `Am I more emotionally available or emotionally guarded?`,
  `What’s one thing that makes me feel instantly safe?`,
  `Who in the group do I vibe with most naturally?`,
  `Do I prefer deep one-on-one convos or chaotic group talks?`,
  `What type of people do I struggle to get along with?`,
  `Am I more of a leader, follower, or observer?`,
  `What role do I play when there’s group conflict?`,
  `Do I usually give advice or just listen?`,
  `How do I show I care about my friends?`,
  `Which of my traits am I most proud of?`,
  `Which trait am I secretly insecure about?`,
  `How would I describe myself in one word?`,
  `What emotion do I hide the best?`,
  `Do I consider myself more optimistic, pessimistic, or realistic?`,
  `Do I overthink things or act on impulse?`,
  `Am I more self-critical or self-forgiving?`,
  `Which mental health struggle do I relate to most?`,
  `Am I more driven by passion or responsibility?`,
  `Do I see myself as misunderstood?`,
  `What motivates me the most: fear, love, ambition, or duty?`,
  `Do I want to be famous, respected, or loved?`,
  `What’s one thing I absolutely want in life, no matter what?`,
  `Am I more likely to chase stability or chase dreams?`,
  `How do I define success for myself?`,
  `What scares me more: failure or being average?`,
  `Would I rather build something meaningful or enjoy a quiet life?`,
  `Do I plan to stay close to home or move far away someday?`,
  `What’s a value I’ll never compromise on?`,
  `Who do I want to become in 10 years?`,
];

export const NEVER_HAVE_I_EVER = [
  `Never have I ever rage quit a game because I was losing.`,
  `Never have I ever pretended to understand something just to look smart.`,
  `Never have I ever developed a crush on an anime character.`,
  `Never have I ever made a meme about one of my friends.`,
  `Never have I ever stayed up all night just listening to music.`,
  `Never have I ever ghosted someone because I didn’t feel like talking.`,
  `Never have I ever argued with a lecturer or teacher.`,
  `Never have I ever had a full conversation in my head instead of out loud.`,
  `Never have I ever used my mental health as an excuse to avoid responsibilities.`,
  `Never have I ever Googled something during a conversation to keep up.`,
  `Never have I ever danced alone in my room.`,
  `Never have I ever written a love letter and never sent it.`,
  `Never have I ever sabotaged a group project because no one listened to me.`,
  `Never have I ever cried over a fictional character's death.`,
  `Never have I ever created a fake scenario in my head to feel something.`,
  `Never have I ever gotten angry and punched something.`,
  `Never have I ever felt like I was the only sane one in the group.`,
  `Never have I ever tried to "fix" someone emotionally.`,
  `Never have I ever overshared and instantly regretted it.`,
  `Never have I ever questioned my sexuality because of a celebrity or character.`,
  `Never have I ever made a joke too dark and immediately regretted it.`,
  `Never have I ever been the therapist friend when I needed therapy myself.`,
  `Never have I ever acted dumb to avoid responsibilities.`,
  `Never have I ever felt invisible even around close friends.`,
  `Never have I ever shut down emotionally mid-conversation.`,
  `Never have I ever lied about how I’m really feeling just to keep the vibe.`,
  `Never have I ever made a playlist just to match my mood.`,
  `Never have I ever comforted someone while I was breaking down inside.`,
  `Never have I ever zoned out mid-lecture and never came back.`,
  `Never have I ever had an emotional breakdown over something small.`,
  `Never have I ever overanalyzed a “k” text for hours.`,
  `Never have I ever avoided a friend because I didn’t know how to act normal around them.`,
  `Never have I ever imagined what my funeral would be like.`,
  `Never have I ever faked a personality to fit into a group.`,
  `Never have I ever developed feelings for someone who barely knew I existed.`,
  `Never have I ever used humor to hide how I really feel.`,
  `Never have I ever ghosted someone just because I didn’t want to deal with the drama.`,
  `Never have I ever talked to myself like I was two different people.`,
  `Never have I ever gotten into a deep conversation at 3 a.m. that changed how I saw someone.`,
  `Never have I ever gone from laughing to crying in under a minute.`,
  `Never have I ever started a fight just because I was already angry at something else.`,
  `Never have I ever felt like the background character in my own life.`,
  `Never have I ever created an entire fake life in my head that I escape to.`,
  `Never have I ever wished I could just disappear for a while.`,
  `Never have I ever stalked a crush’s profile so much I memorized their posts.`,
  `Never have I ever tried to decode a one-word text for hours.`,
  `Never have I ever cried while pretending everything was fine.`,
  `Never have I ever wanted to scream but just stayed silent.`,
  `Never have I ever used anime or music to escape reality.`,
  `Never have I ever fallen for someone I only talked to online.`,
];

export const DEEP_CUTS = [
  `Have you ever felt invisible in a group of people you care about? What did you do?`,
  `What's a moment you wish you had spoken up but stayed silent?`,
  `When have you acted like you didn’t care, but deep down you really did?`,
  `Tell us about a time when your quietness or loudness led to someone misunderstanding you.`,
  `Have you ever faked a personality to fit in socially? How did it feel?`,
  `What’s one thing people never notice about you that matters a lot to you?`,
  `When did someone truly see or understand you for the first time?`,
  `Have you ever been told you were “too much” or “too quiet”? How did that affect you?`,
  `When did you shut people out emotionally? Why?`,
  `Who’s the first person you truly opened up to, and why?`,
  `What's the darkest joke you've ever told that came from a real place of pain?`,
  `Have you ever used humor to cover up something you were really going through?`,
  `Tell us about a time your anger hurt someone you love.`,
  `When have you felt out of control emotionally, and how did you deal with it?`,
  `What's the scariest thing you've ever done impulsively?`,
  `What's something chaotic you did that actually came from a place of sadness?`,
  `Have you ever scared yourself with your own mood swings?`,
  `When did someone finally take your pain seriously behind the jokes?`,
  `What’s the biggest regret you have from acting on emotion?`,
  `What’s the one thing you wish people understood about your wild side?`,
  `When did your intelligence or skills make you feel isolated from others?`,
  `Have you ever been underestimated, and how did you prove people wrong?`,
  `What's one thing you wish people knew about the pressure to always perform well?`,
  `Have you ever burned out trying to live up to expectations?`,
  `When did being “smart” stop being a compliment and start feeling like a burden?`,
  `What part of yourself have you neglected in the pursuit of success?`,
  `Have you ever been bullied or excluded for being different or too “into” something?`,
  `When did someone genuinely appreciate your passion or knowledge?`,
  `What’s one mistake you made that intelligence couldn’t fix?`,
  `What drives you when no one is watching?`,
  `What’s something you struggle with mentally that no one ever sees?`,
  `When was the last time you truly felt hopeless, and what got you through it?`,
  `Have you ever tried to explain your mental state and felt dismissed?`,
  `What's one high or low moment that completely changed your outlook on life?`,
  `When did your optimism or pessimism get you into trouble?`,
  `What does it feel like inside your head on a “bad day”?`,
  `What’s the most painful thing you’ve hidden behind a smile?`,
  `Have you ever just let life “happen” without fighting back? Why?`,
  `What’s one thing that always brings you peace, even briefly?`,
  `When did you finally realize you needed help or support?`,
  `When did you first start questioning or embracing your identity?`,
  `Have you ever felt out of place in your own community?`,
  `What’s something unique about your culture or background that’s shaped you deeply?`,
  `When was your identity challenged, and how did you defend it?`,
  `What’s a moment when you felt deeply proud of who you are?`,
  `Have you ever had to hide a part of yourself from family or friends?`,
  `When did university life break or build a piece of you?`,
  `What’s something painful or beautiful about being a teen today?`,
  `Have you ever faced discrimination or judgment for who you are? What happened?`,
  `What’s one label you carry that people misunderstand the most?`,
  `When did you put someone else’s needs above your own, and suffer for it?`,
  `What’s a moment you protected someone without them even knowing?`,
  `Have you ever felt like the “strong one” but desperately needed help yourself?`,
  `What does it mean to you to be responsible for others?`,
  `When have you felt the weight of being someone’s emotional anchor?`,
  `What’s the most selfless thing you’ve ever done?`,
  `When did someone finally take care of *you* instead?`,
  `Have you ever broken down because you couldn’t be strong anymore?`,
  `What’s the hardest part about always being the protector?`,
  `What’s one lesson you learned from trying to fix everyone?`,
  `What show or song helped you through something you couldn’t talk about?`,
  `When did fandom become your escape, and why did you need that escape?`,
  `Have you ever felt closer to fictional characters than real people?`,
  `What’s one lyric or quote that feels like your soul speaking?`,
  `What moment made you fall in love with music or anime forever?`,
  `Have you ever bonded with someone deeply just over a shared interest?`,
  `What’s one time your obsession actually healed or saved you?`,
  `When did someone mock your passion, and how did it make you feel?`,
  `Which piece of media do you feel represents *you* perfectly?`,
  `What’s something emotional you’ve never said out loud but only felt through anime/music?`,
  `When did someone treat you like you weren’t good enough, and how did you respond?`,
  `What’s a time you were left behind, and how did that affect you?`,
  `What’s one thing you wish people knew about how you see the world?`,
  `Have you ever surprised someone with something they didn’t expect from you?`,
  `When did someone give up on you too soon?`,
  `What’s one strength you’ve discovered in your own pace or style?`,
  `When have you felt completely misunderstood?`,
  `What’s something you achieved that you’re truly proud of, even if others don’t see it?`,
  `Who’s someone that believed in you when no one else did?`,
  `What’s something people assume about you that couldn’t be more wrong?`,
];

export const RAPID_FIRE = [
  `What’s your biggest red flag?`,
  `What’s something you always lie about?`,
  `Who’s most likely to marry rich?`,
  `What’s a toxic trait you secretly admire?`,
  `Who would survive a zombie apocalypse the longest?`,
  `Who’s most likely to disappear and never be found?`,
  `What’s the worst insult someone could throw at you?`,
  `What’s your comfort anime?`,
  `Who in the group would be the final boss in a video game?`,
  `What’s the last thing you searched on Google?`,
  `What’s one thing you’ve stolen before?`,
  `Which friend is secretly the most emotional?`,
  `Who’s most likely to be famous and why?`,
  `What’s a weird flex you have?`,
  `If your mood was a weather forecast, what would it be today?`,
  `Who would sell out the friend group first?`,
  `What’s something you’ll never forgive yourself for?`,
  `What would your villain name be?`,
  `Who’s most likely to date a cartoon character?`,
  `What’s the weirdest compliment you’ve ever gotten?`,
  `Who overthinks everything?`,
  `What’s your most “main character” moment?`,
  `What’s your villain origin story?`,
  `Who’s secretly the freakiest?`,
  `Who’s most likely to cry watching a cartoon?`,
  `What’s your emotional support song?`,
  `Which friend would be the best cult leader?`,
  `What’s one thing you hope your parents never find out?`,
  `What’s your toxic confession?`,
  `Who’s most likely to get arrested for something dumb?`,
  `What do you wish people understood about you?`,
  `What’s one secret you think someone here is hiding?`,
  `What’s the worst personality combo to date?`,
  `Who acts tough but is actually soft?`,
  `Who’s most likely to ghost a relationship for no reason?`,
  `What’s one insecurity that shows up a lot?`,
  `What’s a song that perfectly describes you?`,
  `Who would accidentally start a war?`,
  `What part of your personality scares you the most?`,
  `Who’s most likely to die in a horror movie—and why?`,
  `What’s a personality trait you wish you had?`,
  `Who’s the real main character of this friend group?`,
  `What’s your go-to trauma response?`,
  `If your life had a genre, what would it be?`,
  `Who hides behind humor the most?`,
  `Who’s most likely to disappear for months with no explanation?`,
  `What’s the weirdest thing you’ve cried over?`,
  `What’s something that gives you the ick instantly?`,
  `Who’s most likely to befriend their therapist?`,
  `If you had to fight one person here, who are you choosing?`,
  `What would break you completely?`,
  `What’s one part of your childhood you never talk about?`,
  `Who has the most chaotic brain?`,
  `What’s your most unhinged thought you’ve acted on?`,
  `What’s a mistake you’d 100% make again?`,
  `Who’s most likely to write a dramatic breakup text?`,
  `What’s a truth about yourself you avoid?`,
  `Who’s the loudest during emotional breakdowns?`,
  `What’s your most delusional belief?`,
  `Who’s most likely to betray someone for love?`,
  `What’s one thing you pretend not to care about, but actually do?`,
  `Who hides their emotions the best?`,
  `What’s a “you had to be there” moment you still laugh at?`,
  `Who gives the worst advice with the most confidence?`,
  `What’s your go-to mental escape?`,
  `Who’s most likely to become a sugar baby?`,
  `What’s a lie you tell yourself regularly?`,
  `Who’s most likely to send a risky text then ghost?`,
  `What’s your most irrational fear?`,
  `Who’s the real therapist of this group?`,
  `What’s a habit that ruins your life but you can’t stop?`,
  `Who in this group would be a cult follower and love it?`,
  `What’s a truth about someone here they wouldn’t admit?`,
  `Who’s most likely to fake their death and start over?`,
  `What’s your go-to excuse when you flake?`,
  `Who’s most likely to fall in love with their situationship?`,
  `What’s your worst coping mechanism?`,
  `Who’s most likely to cry during sex?`,
  `What’s one personality trait you can’t stand in others?`,
  `Who’s secretly the most romantic?`,
  `What’s a compliment that lowkey offended you?`,
  `Who has the messiest thoughts but looks put together?`,
  `What’s the weirdest daydream you’ve ever had?`,
  `What’s a personal rule you always break?`,
  `Who gives “emotionally unavailable but clingy” energy?`,
  `What’s a past version of yourself you miss?`,
  `Who’s most likely to break into your house for fun?`,
  `What’s a feeling you can’t describe but know too well?`,
  `Who would be the worst person to be stranded with?`,
  `What’s something you lowkey judge people for?`,
  `Who’s most likely to get famous and regret it?`,
  `What’s one emotion you wish you could turn off?`,
  `Who’s the “it’s not that deep” person, even when it is?`,
  `What’s one trait people assume about you that’s wrong?`,
  `Who’s most likely to throw hands at a family gathering?`,
  `What’s a soft spot you protect aggressively?`,
  `Who has the worst luck with love?`,
  `What’s something you wish you’d never experienced?`,
  `Who’s the most emotionally intelligent person here?`,
  `What’s one memory that always haunts you?`,
];
